// Code generated by rice embed-go; DO NOT EDIT.
package daggenerate

import (
	"time"

	"github.com/GeertJohan/go.rice/embedded"
)

func init() {

	// define files
	file2 := &embedded.EmbeddedFile{
		Filename:    "google-analytics.txt",
		FileModTime: time.Unix(1606613344, 0),

		Content: string("Google Analytics Source Code :)\nGoogle Analytics Source Code :)\nGoogle Analytics Source Code :)\nGoogle Analytics Source Code :)\nGoogle Analytics Source Code :)\nGoogle Analytics Source Code :)\nGoogle Analytics Source Code :)\n"),
	}

	// define dirs
	dir1 := &embedded.EmbeddedDir{
		Filename:   "",
		DirModTime: time.Unix(1606613344, 0),
		ChildFiles: []*embedded.EmbeddedFile{
			file2, // "google-analytics.txt"

		},
	}

	// link ChildDirs
	dir1.ChildDirs = []*embedded.EmbeddedDir{}

	// register embeddedBox
	embedded.RegisterEmbeddedBox(`sources`, &embedded.EmbeddedBox{
		Name: `sources`,
		Time: time.Unix(1606613344, 0),
		Dirs: map[string]*embedded.EmbeddedDir{
			"": dir1,
		},
		Files: map[string]*embedded.EmbeddedFile{
			"google-analytics.txt": file2,
		},
	})
}

func init() {

	// define files
	file4 := &embedded.EmbeddedFile{
		Filename:    "snowflake.txt",
		FileModTime: time.Unix(1606613344, 0),

		Content: string("Snowflake Destination Code\nSnowflake Destination Code\nSnowflake Destination Code\nSnowflake Destination Code\nSnowflake Destination Code\nSnowflake Destination Code\nSnowflake Destination Code\nSnowflake Destination Code\n"),
	}

	// define dirs
	dir3 := &embedded.EmbeddedDir{
		Filename:   "",
		DirModTime: time.Unix(1606613344, 0),
		ChildFiles: []*embedded.EmbeddedFile{
			file4, // "snowflake.txt"

		},
	}

	// link ChildDirs
	dir3.ChildDirs = []*embedded.EmbeddedDir{}

	// register embeddedBox
	embedded.RegisterEmbeddedBox(`destinations`, &embedded.EmbeddedBox{
		Name: `destinations`,
		Time: time.Unix(1606613344, 0),
		Dirs: map[string]*embedded.EmbeddedDir{
			"": dir3,
		},
		Files: map[string]*embedded.EmbeddedFile{
			"snowflake.txt": file4,
		},
	})
}
